---
version: "3.5"
services:
  postfix:
    image: postfixdocker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - stack.env
    networks:
      - mail
networks:
  mail:
    name: mail
